cue-lang/cuelang.org

- .github/workflows/test.yml
- config/_default/config.toml
- netlify.toml
- package-lock.json
- package.json
- play/go.mod
- play/go.sum
As reported by npm audit.
Also bump the versions of Go and Node that we are using.
> deps: fix up bad npm deps

- static/golang/go.html
> general: remove another godoc reference

- netlify.toml
This addresses advisory:
https://github.com/advisories/GHSA-8j34-9876-pvfq
> deps: use latest version of Hugo

- .github/workflows/test.yml
- .gitignore
- README.md
- netlify.toml
- play/go.mod
- play/go.sum
> deps: use latest Hugo and Go versions ahead of upgrading docsy

- netlify.toml
> deps: revert to using go1.16.10

- netlify.toml
- play/go.mod
- play/go.sum
> deps: use Go 1.17.3 and latest playground

- netlify.toml
- package-lock.json
> deps: bump node version to v16.13.0

- content/en/docs/concepts/logic.md
> concetps: fix inconsistent capitalization of TypeScript

- content/en/docs/tutorials/kubernetes.md
- content/en/pkg.go.dev.md
- go.mod
- go.sum
- package-lock.json
> deps: use latest CUE

- go.mod
- go.sum
- play/go.mod
- play/go.sum
> deps: use latest playground

- content/en/docs/contribution_guidelines/_index.md
> docs: update contribution guide to mention DCO

- content/en/_index.html
- content/en/docs/install/_index.md
- netlify.toml
> doc: fix up install instructions

- content/en/docs/integrations/protobuf.md
> docs/integrations/protobuf: fix Go example formatting

- content/en/docs/usecases/configuration.md
Reverts cue-lang/cuelang.org#227
> Revert "fix typo"

- content/en/docs/about/_index.md
Signed-off-by: Marco Abis <marco.abis@gmail.com>
> typo: plural should be singular

- play/go.mod
- play/go.sum
> play: update to latest playground version

- internal/functions/gerritstatusupdater/gerritstatusupdater.go
> gerritstatusupdater: fail any completed job that did not succeed

- internal/functions/gerritstatusupdater/gerritstatusupdater.go
> gerritstatusupdater: workarounds for broken GitHub event state

- internal/functions/gerritstatusupdater/gerritstatusupdater.go
> gerritstatusupdater: more logging to help confirm GitHub fixes

- layouts/docs/tutorial.html
- layouts/partials/head.html
> all: make all Permalink's RelPermalink's

- .github/workflows/test.yml
> CI: use Go 1.19.x

- README.md
> doc: signpost to the main CUE repo for issue tracking

- netlify.toml
> site: add redirect from /discussions to match /discussion

- build.bash
- play/build.bash
> ci: ensure tip always uses non-proxy-cached master

- play/package-lock.json
> deps: fix CVE-2022-37601 by running npm audit fix

- netlify.toml
> all: add short link to community calendar

- config/_default/config.toml
- config/tip/config.toml
- content/en/_index.html
- content/zh/_index.html
- content/zh/docs/install/_index.md
> all: switch to using / as baseURL
